export function renderPortableUi(nonce) {
    return `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Print Drive 휴대형 업데이터</title>
<style>
:root{color-scheme:light;--ink:#142033;--muted:#657187;--line:#d8e0eb;--blue:#2457d6;--soft:#f4f7fb;--ok:#087a55;--warn:#a34d00}*{box-sizing:border-box}body{font-family:Inter,"Pretendard",system-ui,sans-serif;margin:0;background:linear-gradient(145deg,#eef3ff,#f8fafc 42%);color:var(--ink)}main{max-width:920px;margin:auto;padding:40px 20px 72px}.eyebrow{color:var(--blue);font-weight:800;letter-spacing:.08em;text-transform:uppercase}.hero{margin-bottom:28px}.hero h1{font-size:clamp(2rem,5vw,3.2rem);line-height:1.04;margin:.3rem 0 .8rem}.hero p{max-width:680px;color:var(--muted);font-size:1.05rem}.steps{display:grid;gap:14px}.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:22px;box-shadow:0 8px 30px #243b6410}.card h2{margin:0 0 5px;font-size:1.15rem}.step{display:flex;gap:14px}.num{width:30px;height:30px;flex:0 0 auto;border-radius:50%;background:#e8efff;color:var(--blue);display:grid;place-items:center;font-weight:800}.content{min-width:0;flex:1}.muted,.help{color:var(--muted);font-size:.92rem}.path{word-break:break-all;padding:11px 13px;background:var(--soft);border-radius:9px;margin:12px 0}label{display:block;margin:14px 0 6px;font-weight:700}input,select,textarea,button{font:inherit}input:not([type=checkbox]),select,textarea{width:100%;padding:11px 12px;border:1px solid #aeb9ca;border-radius:9px;background:#fff}input:focus,select:focus,textarea:focus,button:focus-visible,a:focus-visible{outline:3px solid #9db8ff;outline-offset:2px}button,.button-link{border:0;border-radius:9px;background:var(--blue);color:white;padding:10px 14px;font-weight:750;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}button.secondary,.button-link.secondary{background:#eef2f8;color:#28364e;border:1px solid var(--line)}button.ghost{background:transparent;color:#44536b;border:1px solid var(--line)}button:disabled{opacity:.45;cursor:not-allowed}.row{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.check{display:flex;gap:9px;align-items:flex-start;font-weight:600}.check input{margin-top:3px}.auth-box{border:1px solid #bfd0fa;background:#f6f8ff;border-radius:12px;padding:14px;margin-top:12px}.auth-state{font-weight:750;color:var(--warn)}.auth-state.ok{color:var(--ok)}.plan-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.plan-group{border:1px solid var(--line);border-radius:10px;padding:12px}.plan-group h3{font-size:.92rem;margin:0 0 7px}.plan-group ul{margin:0;padding-left:20px;color:#3d4a5e}.metric{font-variant-numeric:tabular-nums;font-weight:750}.status{white-space:pre-wrap;background:#172033;color:#f5f7fb;padding:14px;border-radius:11px;min-height:54px;margin-top:12px}.hidden{display:none!important}.result{border-left:4px solid var(--ok)}@media(max-width:640px){main{padding:24px 12px 48px}.card{padding:17px}.plan-grid{grid-template-columns:1fr}.row>*{width:100%}}
</style></head>
<body><main><header class="hero"><div class="eyebrow">Print Drive · Windows x64</div><h1>암호화 업데이트를<br>끝까지 확인하세요</h1><p>평문 파일, vault 비밀번호, GitHub token은 이 컴퓨터의 실행 메모리에서만 처리됩니다. GitHub에는 암호문만 전송합니다.</p></header>
<div class="steps">
<section class="card step"><div class="num">1</div><div class="content"><h2>시작</h2><p class="muted" id="repository">설정을 불러오는 중…</p><p class="help">적용 전 정확한 기준 commit을 다시 확인하며, GitHub commit과 Pages 배포 확인을 별도 상태로 표시합니다.</p></div></section>
<section class="card step"><div class="num">2</div><div class="content"><h2>원본 폴더</h2><div class="path" id="source-path">불러오는 중…</div><p class="muted" id="source-meta"></p><div class="row"><button class="secondary" id="source-open">Workspace 폴더 열기</button><button class="secondary" id="source-select">다른 폴더 선택</button><button class="ghost" id="source-refresh">폴더 다시 읽기</button></div><p class="help">선택한 경로는 설정 파일에 저장되지 않으며 이 실행이 끝나면 잊습니다.</p></div></section>
<section class="card step"><div class="num">3</div><div class="content"><h2>Vault와 작업 방식</h2><label for="password">Vault 비밀번호</label><input id="password" type="password" autocomplete="off"><label for="mode">업데이트 모드</label><select id="mode"><option value="add-replace">추가/교체 — 원격 전용 파일 유지 (권장)</option><option value="remove-selected">선택 삭제 + 추가/교체</option><option value="mirror">원본 폴더와 완전히 동일하게 맞추기 (고급)</option></select><label for="removals">삭제할 원격 상대 경로 · 한 줄에 하나</label><textarea id="removals" rows="3"></textarea><label class="check"><input id="empty-confirm" type="checkbox"><span>빈 폴더로 mirror할 때 원격 파일 전체 삭제를 한 번 더 확인합니다.</span></label></div></section>
<section class="card step"><div class="num">4</div><div class="content"><h2>GitHub 인증</h2><p class="muted">Fine-grained token이 기본 방식입니다. token은 검증 후 입력창에서 즉시 지우고, 성공·취소·종료 시 메모리에서도 지웁니다.</p><div class="auth-box"><label for="pat">Fine-grained personal access token</label><input id="pat" type="password" autocomplete="off" spellcheck="false"><div class="row" style="margin-top:10px"><button id="pat-auth">Token 검증</button><a class="button-link secondary" href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noreferrer">GitHub에서 token 만들기</a></div><p class="help">Repository access: <strong>Only select repositories → BJDG-CM/print-drive</strong>. Permissions: <strong>Contents · Read and write</strong>, Metadata · Read. 브랜치 보호 fallback PR까지 쓰려면 Pull requests · Read and write도 추가하세요.</p></div><div id="device-area" class="auth-box hidden"><p class="muted">이 패키지에는 선택형 Device Flow도 설정되어 있습니다.</p><button class="secondary" id="device">GitHub 기기 로그인</button></div><p id="auth-state" class="auth-state">인증 필요</p></div></section>
<section class="card step"><div class="num">5</div><div class="content"><h2>변경 계획</h2><button id="preview">원격 기준 확인 및 암호화 미리보기</button><div id="plan" class="hidden"><p><span class="metric" id="plan-base"></span><br><span class="metric" id="plan-size"></span></p><div class="plan-grid" id="plan-grid"></div></div></div></section>
<section class="card step"><div class="num">6</div><div class="content"><h2>적용</h2><label class="check"><input id="apply-confirm" type="checkbox"><span id="apply-copy">변경 계획을 먼저 만드세요.</span></label><div class="row" style="margin-top:12px"><button id="apply" disabled>암호화 업데이트 적용</button><button id="fallback" class="secondary hidden">업데이트 브랜치와 PR 만들기</button><button id="cancel" class="ghost">취소하고 비밀정보 지우기</button></div><div id="status" class="status" role="status" aria-live="polite">준비됨</div></div></section>
<section class="card step result hidden" id="result"><div class="num">7</div><div class="content"><h2>결과</h2><div id="result-body"></div></div></section>
</div></main><script nonce="${nonce}">
const query=location.search;let csrf='';let lastPlan=null;const byId=id=>document.getElementById(id);const status=byId('status');
async function call(route,body){const response=await fetch(route+query,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json','x-print-drive-csrf':csrf},body:body===undefined?undefined:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Object.assign(new Error(value.error||'요청 실패'),value);return value}
function showSource(source){byId('source-path').textContent=source.path;byId('source-meta').textContent=source.files.toLocaleString()+'개 파일 · '+formatBytes(source.bytes)}
function formatBytes(value){if(value<1024)return value+' B';if(value<1048576)return (value/1024).toFixed(1)+' KiB';return (value/1048576).toFixed(1)+' MiB'}
function setAuth(ok,message){byId('auth-state').textContent=message;byId('auth-state').classList.toggle('ok',ok)}
function listGroup(title,values){const box=document.createElement('div');box.className='plan-group';const heading=document.createElement('h3');heading.textContent=title+' · '+values.length;box.append(heading);const list=document.createElement('ul');for(const value of values.length?values:['없음']){const item=document.createElement('li');item.textContent=typeof value==='string'?value:value.from+' → '+value.to;list.append(item)}box.append(list);return box}
function showPlan(value){lastPlan=value;byId('plan').classList.remove('hidden');byId('plan-base').textContent='기준 commit '+value.baseSha;byId('plan-size').textContent='변경 '+value.changeCount+'건 · 암호화 업로드 '+formatBytes(value.uploadBytes);const grid=byId('plan-grid');grid.replaceChildren(listGroup('추가',value.plan.additions),listGroup('교체',value.plan.replacements),listGroup('이동',value.plan.moves),listGroup('삭제',value.plan.removals),listGroup('변경 없음',value.plan.unchanged));byId('apply-copy').textContent='변경 '+value.changeCount+'건, 암호화 업로드 '+formatBytes(value.uploadBytes)+', 기준 '+value.baseSha.slice(0,12)+'를 확인했습니다.';byId('apply').disabled=false}
function showResult(value){const result=byId('result');const body=byId('result-body');body.replaceChildren();const lines=[];if(value.direct){lines.push('Git commit: '+value.commitSha);lines.push(value.deployment?.status==='confirmed'?'Pages 배포 확인됨 · '+value.deployment.manifestSha256:'Pages 배포 '+(value.deployment?.status||'확인 실패')+' · '+(value.deployment?.reason||''));}else{lines.push('배포되지 않음 — PR 병합 필요');lines.push('PR: '+value.pullRequestUrl)}for(const line of lines){const p=document.createElement('p');p.textContent=line;body.append(p)}if(value.pagesUrl){const link=document.createElement('a');link.href=value.pagesUrl;link.target='_blank';link.rel='noreferrer';link.textContent='공개 Print Drive 열기';body.append(link)}result.classList.remove('hidden');result.scrollIntoView({behavior:'smooth'})}
call('/api/session').then(v=>{csrf=v.csrf;byId('repository').textContent=v.owner+'/'+v.repo+' · '+v.branch;showSource(v.source);byId('device-area').classList.toggle('hidden',!v.deviceFlowConfigured);setAuth(v.authenticated,v.authenticated?'인증됨':'인증 필요')}).catch(e=>status.textContent=e.message);
byId('source-open').onclick=async()=>{try{await call('/api/source/open',{});status.textContent='원본 폴더를 열었습니다.'}catch(e){status.textContent=e.message}};
byId('source-select').onclick=async()=>{try{status.textContent='Windows 폴더 선택 창을 기다리는 중…';const v=await call('/api/source/select',{});showSource(v.source);status.textContent=v.cancelled?'폴더 선택을 취소했습니다.':'새 원본 폴더를 선택했습니다.';lastPlan=null;byId('apply').disabled=true}catch(e){status.textContent=e.message}};
byId('source-refresh').onclick=async()=>{try{const v=await call('/api/source/refresh',{});showSource(v.source);status.textContent='폴더를 다시 읽었습니다.';lastPlan=null;byId('apply').disabled=true}catch(e){status.textContent=e.message}};
byId('pat-auth').onclick=async()=>{const input=byId('pat');try{status.textContent='Token과 저장소 권한을 확인하는 중…';await call('/api/auth/pat',{token:input.value});setAuth(true,'인증됨 · token은 이 실행의 메모리에만 보관');status.textContent='GitHub 인증과 저장소 접근을 확인했습니다.'}catch(e){setAuth(false,'인증 실패');status.textContent=e.message}finally{input.value=''}};
byId('device').onclick=async()=>{try{const v=await call('/api/device/start',{});status.textContent='코드 '+v.userCode+'를 '+v.verificationUri+'에 입력하세요.\n승인을 기다리는 중…';await call('/api/device/poll',{});setAuth(true,'인증됨 · Device Flow');status.textContent='GitHub 인증과 저장소 접근을 확인했습니다.'}catch(e){setAuth(false,'인증 실패');status.textContent=e.message}};
byId('preview').onclick=async()=>{status.textContent='정확한 원격 snapshot을 가져와 로컬에서 암호화하는 중…';const password=byId('password');try{const v=await call('/api/preview',{passphrase:password.value,mode:byId('mode').value,removePaths:byId('removals').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),confirmEmptyMirror:byId('empty-confirm').checked});showPlan(v);status.textContent='변경 계획이 준비됐습니다. 적용 확인을 검토하세요.'}catch(e){status.textContent=e.message}finally{password.value=''}};
byId('apply').onclick=async()=>{if(!byId('apply-confirm').checked){status.textContent='적용 확인 체크박스를 선택하세요.';return}try{status.textContent='원격 기준을 재확인하고 단일 commit을 만든 뒤 Pages 반영을 확인하는 중…';const v=await call('/api/apply',{confirm:true});showResult(v);status.textContent=v.deployment?.status==='confirmed'?'Git commit과 공개 Pages 산출물을 모두 확인했습니다.':'Git commit은 완료됐지만 Pages는 아직 확인 대기 상태입니다.';setAuth(false,'작업 완료 · token 삭제됨')}catch(e){status.textContent=e.message;if(e.canFallback)byId('fallback').classList.remove('hidden')}};
byId('fallback').onclick=async()=>{try{const v=await call('/api/fallback',{});showResult(v);status.textContent='업데이트 PR을 만들었습니다. 병합 전에는 배포되지 않습니다.';setAuth(false,'작업 완료 · token 삭제됨')}catch(e){status.textContent=e.message}};
byId('cancel').onclick=async()=>{try{await call('/api/cancel',{});byId('pat').value='';byId('password').value='';lastPlan=null;byId('apply').disabled=true;byId('apply-confirm').checked=false;setAuth(false,'취소됨 · token 삭제됨');status.textContent='대기 작업과 메모리 token을 지웠습니다.'}catch(e){status.textContent=e.message}};
</script></body></html>`;
}
